name: CI
on:
  #schedule:
  #  - cron: '30 5 * * *'

  push:
    branches:
      - main
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        nim: ['devel', 'version-1-6']
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ci

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Setup Lua
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libluajit-5.1-dev liblua5.1-0-dev

      - name: Setup Tree-Sitter
        if: ${{ matrix.os }} == 'ubuntu-latest'
        env:
          TS_VERSION: "0.20.0"
        shell: bash
        run: |
          wget "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${TS_VERSION}.tar.gz"
          tar -xvf "v${TS_VERSION}.tar.gz"
          cd "tree-sitter-${TS_VERSION}"
          sudo make install PREFIX=/usr

      - name: Run tests
        shell: bash
        run: |
          cd ci
          nimble --accept develop
          balls --define:release --define:danger --gc:arc --backend:c --threads:on

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        shell: bash
        run: |
          cd ci
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --gc:arc --threads:on --project --path="." --outdir:docs \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            gread.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
          matrix.os == 'ubuntu-latest' && matrix.nim == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: ci/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
